# Generated by Django 3.0.5 on 2021-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\shi95\\PycharmProjects\\lastback\\backend\\mediauser_id'),
        ),
        migrations.AlterField(
            model_name='people',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
